logPath: 'log/app.log'
httpServer:
  port: 8888
  apiKey: '123fish'
webSocketServer:
  port: 8188
janus:
  webSocketAddress: 'ws://198.23.87.26:8188/janus'
  httpAddress: 'http://198.23.87.26:8188/janus'
cmApi:
  baseUrl: 'http://www.cm.dev/rpc/null'
  apiKey: '123fish'
cmApplication:
  path: '/home/cm'
jobManager:
  jobsPath: '/tmp'
