mod 'cargomedia/nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/fluentd',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/fluentd'
